# =========================================================
# APPLICATION
# =========================================================

spring.application.name=api-gateway
server.port=8080


# =========================================================
# SPRING CLOUD GATEWAY
# =========================================================

# ---------------------------------------------------------
# EMPLOYEE AUTHENTICATION
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[0].id=employee-auth-service

spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth,/api/v1/auth/**


# ---------------------------------------------------------
# EMPLOYEE SERVICE
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[1].id=employee-service

spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/employees,/api/v1/employees/**


# ---------------------------------------------------------
# LEAVE TYPE SERVICE
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[2].id=leave-service

spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082

spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/leave-types,/api/v1/leave-types/**


# ---------------------------------------------------------
# LEAVE REQUEST SERVICE
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[3].id=leave-service-requests

spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8082

spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/leave-requests,/api/v1/leave-requests/**


# ---------------------------------------------------------
# LEAVE BALANCE SERVICE
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[4].id=leave-service-balances

spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8082

spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/leave-balances,/api/v1/leave-balances/**


# ---------------------------------------------------------
# NOTIFICATION SERVICE
# ---------------------------------------------------------

spring.cloud.gateway.server.webflux.routes[5].id=notification-service

spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8083

spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/notifications,/api/v1/notifications/**


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=never


# =========================================================
# LOGGING
# =========================================================

logging.level.org.springframework.cloud.gateway=INFO

logging.level.org.springframework.security=INFO